### ISSUE TITLE
Possibilitée de spam l'hebdoo

### ISSUE THREAD

**Issue by Jokod** [tonnevillec/tutomarks#98]
Récemment, certains utilisateurs ont commencé à spammer l'ajout de ressources sur la section"Hebdoo", en utilisant des tentatives d'injection SQL. Pour y remédier, voici quelques solutions possibles :

- Demander la validation par e-mail à l'utilisateur lorsqu'il ajoute une ressource (s'il n'est pas connecté). Cette étape de confirmation par e-mail peut aider à réduire le spam en demandant une validation de la part de l'utilisateur avant que la ressource ne soit ajoutée. Toutefois, cette étape peut rendre le processus d'ajout de ressources plus fastidieux pour les utilisateurs, surtout s'ils doivent attendre un certain temps avant de recevoir l'e-mail de confirmation.

- Mettre en place une vérification CAPTCHA : cette mesure de sécurité peut empêcher les bots automatisés d'ajouter des ressources en spam. Un CAPTCHA peut demander à l'utilisateur de résoudre un puzzle ou une question simple pour vérifier qu'il est bien un humain.

- Limiter le nombre de ressources ajoutées : en limitant le nombre de ressources qu'un utilisateur peut ajouter sur une période donnée, vous pouvez réduire la quantité de spam qui peut être ajoutée en une seule fois.

- Mettre en place une modération de contenu : en utilisant une modération de contenu, vous pouvez passer en revue les ressources ajoutées avant de les publier sur la plateforme, ce qui peut aider à supprimer le spam.

- Utiliser une liste noire : une liste noire de mots-clés couramment utilisés dans les spams peut être utile pour empêcher les utilisateurs d'ajouter des ressources contenant ces mots-clés.

- Encourager la communauté à signaler le spam : en incitant les utilisateurs à signaler le spam, vous pouvez réduire sa propagation et améliorer la qualité globale des ressources sur votre plateforme.

**Comment by tonnevillec** [comment]
Merci pour cette issue.
Je vais regarder quoi faire pour empécher le spam et je penses malheureusement que ca passera par la suppression de la partie Hedboo car depuis que celle_ci est arrivée sur Tutomarks elle n'a malheureusement pas fonctionnée comme je l'espérais
